CARDWORDS = "static/cardwords.txt"
DICTS_DIR = "dicts/"

LABELS_DIR = "labels/"
TRAIN_LABELS = "output/train_labels.json"
TEST_LABELS = "output/test_labels.json"
NEGATIVE_LABELS = "labels/negative_labels.json"
POSITIVE_LABELS = "labels/positive_labels.json"
SCENARIOS = "labels/scenarios.json"
CLUE_THRESHOLDS = "labels/clue_threshold.json"